### PR TITLE
crown beside top user in ulist

### PR DESCRIPTION
**Pull request by gamerlogan819**
yw

### CODE REVIEW

**Comment by 3r1s-s** [comment]
These things are perfect ideas for plugins

**Comment by gamerlogan819** [comment]
> These things are perfect ideas for plugins

there too many plugins

**Comment by 3r1s-s** [comment]
> > These things are perfect ideas for plugins
> 
> 
> 
> there too many plugins

no such thing

**Comment by gamerlogan819** [comment]
> > > These things are perfect ideas for plugins
> > 
> > 
> > there too many plugins
> 
> no such thing

yes there is and this isnt big enough to make a plugin

**Pull request closed without merging**
