### PR TITLE
Comment in first line in worsemeower.js

### PR DESCRIPTION
**Pull request by mybearworld**
Why was that line commented out??
https://github.com/3r1s-s/meo/commit/8bb5233ccc731477e83c7717e8430a8013413781

### CODE REVIEW

**Comment by roblox888i235** [comment]
Send screenshot

**Comment by 3r1s-s** [comment]
Too spammy might disable fr in the future

**Comment by mybearworld** [comment]
oh, sad

**Comment by roblox888i235** [comment]
i would close

**Comment by mybearworld** [comment]
> i would close

Oh yeah, you're right

**Pull request closed without merging**
