### PR TITLE
coolest update

### PR DESCRIPTION
**Pull request by EngineerRunner**
adds
- engineerrunner language
- more whar and qhar

### CODE REVIEW

**Review by delusionsGH — APPROVED** [review]
ok

**Review by EngineerRunner — COMMENTED** [review]
engineer gaming

**Review by Supernoodles99 — APPROVED** [review]
engineer gaming

**Review by mybearworld — APPROVED** [review]
🐻

**Comment by EngineerRunner** [comment]
screw you

**Pull request closed without merging**
